# HTTP -> HTTPS (hopefully???)
<VirtualHost *:80>
    ServerName oseda.net
    ServerAlias www.oseda.net

    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [L,R=301]
</VirtualHost>

HTTPS app and proxy
<VirtualHost *:443>
    ServerName oseda.net
    ServerAlias www.oseda.net

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/oseda.net/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/oseda.net/privkey.pem

    ProxyPreserveHost On
    ProxyRequests Off

    ProxyPass /api/ http://localhost:3001/
    ProxyPassReverse /api/ http://localhost:3001/

    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/

    ErrorLog ${APACHE_LOG_DIR}/oseda_ssl_error.log
    CustomLog ${APACHE_LOG_DIR}/oseda_ssl_access.log combined
</VirtualHost>
